version: '2'

services:
  crm-postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
  crm-php-fpm:
    build:
      context: ./docker/php/dev
      dockerfile: docker-php-fpm
    links:
      - crm-postgres
  crm-php-ws:
    build:
      context: ./docker/php/dev
      dockerfile: docker-php-ws
    ports:
      - "8081"
    volumes:
      - ./:/var/www/crm
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
  crm-nginx:
    image: nginx:1.11
    ports:
      - "80:80"
    depends_on:
      - crm-php-fpm
      - crm-php-ws
    volumes:
      - ./:/var/www/crm
      - ./docker/nginx/conf.d/crm.conf.dev:/etc/nginx/conf.d/crm.conf
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/ws-http.conf:/etc/nginx/ws-http.conf
  crm-rabbitmq:
    build:
      context: ./docker
      dockerfile: docker-rabbitmq
    hostname: crm-rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=ERLANGCOOKIE
      - RABBITMQ_DEFAULT_USER=default_user
      - RABBITMQ_DEFAULT_PASS=default_pass
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "1883:1883"
      - "15672:15672"
      - "15671:15671"